# netlify.toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 301
